name: codespell

on: pull_request

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_file: .codespellignore
          only_warn: 1
          path: docs