name: autofix-prettier
on:
  pull_request:
  push:
    branches: [ "master" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - run: npm ci
      - run: npx prettier --write .

      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
