name: 'Check spelling'
on:
  pull_request:
  push:

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v5
        with:
        files: ''
        root: 'docs/'
        inline: warning
        strict: false
        incremental_files_only: true
        config: '.cspell.json'
        verbose: false
