name: 'Check spelling'
on:
  pull_request:
    branches: [master]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v5
        with:
          github_token: ${{ secrets.CSPELL_TOKEN }}
          files: |
            **/*.{md,mdx}
          inline: warning
          strict: false
          incremental_files_only: true
          config: '.cspell.json'
          verbose: false
        
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          github_token: ${{ secrets.CSPELL_TOKEN }}
          prettier_options: --write **/*.{md,mdx}
          only_changed: True
